name: Build VBox APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone VBox Source
        run: git clone https://github.com/wzxxcz/vbox app-source

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Prepare Signing Config
        working-directory: app-source
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks
          echo "RELEASE_STORE_FILE=./keystore.jks" >> gradle.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> gradle.properties

      - name: Add Signing to Build Config
        working-directory: app-source
        run: |
          sed -i '/android {/a\    signingConfigs {\n        release {\n            storeFile file(RELEASE_STORE_FILE)\n            storePassword RELEASE_STORE_PASSWORD\n            keyAlias RELEASE_KEY_ALIAS\n            keyPassword RELEASE_KEY_PASSWORD\n            v1SigningEnabled true\n            v2SigningEnabled true\n            enableV3Signing = true\n            enableV4Signing = true\n        }\n    }' app/build.gradle
          sed -i '/release {/a\        signingConfig signingConfigs.release' app/build.gradle

      - name: Build APK
        working-directory: app-source
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: VBox-Release
          path: app-source/app/build/outputs/apk/release/*.apk
