name: Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Clone vbox
        run: |
          git clone https://github.com/wzxxcz/vbox TVBoxOSC
          cd TVBoxOSC
          echo "tag=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Add Sign Config
        working-directory: TVBoxOSC
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.jks
          cat >> gradle.properties << EOF
RELEASE_STORE_FILE=./keystore.jks
RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
EOF
          cat > sign.gradle << 'EOF'
signingConfigs {
    release {
        storeFile file(RELEASE_STORE_FILE)
        storePassword RELEASE_STORE_PASSWORD
        keyAlias RELEASE_KEY_ALIAS
        keyPassword RELEASE_KEY_PASSWORD
        v1SigningEnabled true
        v2SigningEnabled true
        enableV3Signing = true
        enableV4Signing = true
    }
}
EOF
          sed -i '/android {/r sign.gradle' app/build.gradle
          sed -i '/release {/a signingConfig signingConfigs.release' app/build.gradle

      - name: Build APK
        working-directory: TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: VBox-${{ env.tag }}
          path: TVBoxOSC/app/build/outputs/apk/release/*.apk
